QUERY_REWRITER_USER_PROMPT = """"""
QUERY_REWRITER_SYSTEM_PROMPT = """"""

SEARCH_PLAN_USER_PROMPT = """"""
SEARCH_PLAN_SYSTEM_PROMPT = """"""

EVALUATION_AGENT_USER_PROMPT = """"""
EVALUATION_AGENT_SYSTEM_PROMPT = """"""
